name: Pull request workflow

on:
  - pull_request
  - workflow_dispatch

jobs:
  test_build_app:
    uses: ./.github/workflows/build_app.yml
  
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
